anotador_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("web.urls")),
    path("admin/", admin.site.urls),
]

web/urls.py
from django.urls import path, include

from . import views

app_name = "web"

urlpatterns = [
    path("", views.home, name="home"),
    path("crear_tarea/", views.crear_tarea, name="crear_tarea"),
    path("borrar_tarea/<int:pk>", views.borrar_tarea, name="borrar_tarea"),
]

web/models.py
import datetime

from django.db import models


# Create your models here.
class Tarea(models.Model):
    tarea = models.CharField(max_length=140)
    dia = models.DateField(default=datetime.date.today)
    hora = models.TimeField()

    def __str__(self):
        return "{0} - {1} - {2}".format(self.tarea[:30], self.dia, self.hora)

web/forms.py
from django import forms

from .models import Tarea


# class TareaForm(forms.Form):
#     tarea = forms.CharField(label="Tarea:", max_length=140)
#     dia = forms.DateField(label="Día:")
#     hora = forms.TimeField(label="Hora:")


class TareaModelForm(forms.ModelForm):
    class Meta:
        model = Tarea
        fields = [
            "tarea",
            "dia",
            "hora",
        ]

        widgets = {
            "tarea": forms.TextInput(attrs={"class": "form-control",}),
            "dia": forms.TextInput(attrs={"class": "form-control",}),
            "hora": forms.TextInput(attrs={"class": "form-control",}),
        }

web/views.py
from django.shortcuts import render, redirect
from .models import Tarea
from .forms import TareaModelForm

# Create your views here.
def home(request):
    form = TareaModelForm()
    context = {
        "tareas": Tarea.objects.all(),
        "form": form,
    }
    return render(request, template_name="web/index.html", context=context)


def crear_tarea(request):

    form = TareaModelForm(request.POST or None)

    if form.is_valid():
        form.save()
        form = TareaModelForm()

    return redirect("/")


def borrar_tarea(request, pk):

    Tarea.objects.filter(id=pk).delete()

    return redirect("/")

web/templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- CSS-Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />

    <!-- Custom-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>{% block title %} {% endblock %}</title>
  </head>

  <body>
    {% block content %} {% endblock %}
  </body>
</html>

web/templates/web/index.html
<!-- prettier-ignore -->
{% extends 'web/base.html' %} 

{% block title %}Anotador en Django{% endblock %}

{% block content %}

<h1>Anotador-Django</h1>

<!-- prettier-ignore -->
<div class="row justify-content-center">  
  <div class="col-md-6">
    <div class="form-group"></div>
      <form action="{% url 'web:crear_tarea' %}" method="POST">{% csrf_token %}
        
        {{ form.as_p }}
        <p><input class="btn btn-primary" type="submit" value="Crear tarea" /></p>

      </form>
    </div>
  </div>
</div>
{% if tareas %}
<hr />

<div class="table-responsive-md">
  <table class="table">
    <thead>
      <tr class="text-center">
        <th scope="col">id</th>
        <th scope="col">Tarea</th>
        <th scope="col">Día</th>
        <th scope="col">Hora</th>
        <th scope="col">Borrar</th>
      </tr>
    </thead>
    <tbody>
      {% for tarea in tareas %}
      <tr class="text-center">
        <th scope="row">{{ tarea.id }}</th>
        <td style="word-wrap: break-word">{{ tarea.tarea }}</td>
        <td>{{ tarea.dia }}</td>
        <td>{{ tarea.hora }}</td>
        <td>
          <!-- prettier-ignore -->
          <form action="{% url 'web:borrar_tarea' tarea.id %}" method="POST">{% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Borrar tarea" />
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<!-- prettier-ignore -->

{% endif %} 

{% endblock %}